### ISSUE TITLE
Submit point: expert / easy mode

### ISSUE THREAD

**Issue by hugoroy** [tosdr/tosdr-build#8]
I have created a new branch for this feature: https://github.com/tosdr/tosdr-build/tree/expert-submit-feature

**TODO**
- [ ] toggle easy / expert mode (inside `<legend></legend>`)
- [ ] depending on the mode, some elements show up or not (see fields with class `expert-mode`)
- [ ] remember the mode when the user comes back to the submit point page
- [ ] if a point's id is specified in the URL, then the form should be able to edit the point's fields
